### ISSUE TITLE
crypto.js error

### ISSUE THREAD

**Issue by rudimk** [rudimk/neu-berliner#3]
When accessing an app with a GET request, the app crashes with this dump:

```
vagrant@raring64-vanilla:~$ coffee testapp.coffee

crypto.js:570
    return binding.PBKDF2(password, salt, iterations, keylen, callback);
                   ^
TypeError: Not a buffer
  at pbkdf2 (crypto.js:570:20)
  at Object.exports.pbkdf2 (crypto.js:556:10)
  at pbkdf2 (/home/vagrant/node_modules/berliner/node_modules/vault-cipher/lib/vault-cipher.js:4:10)
  at [object Object].Cipher.deriveKeys (/home/vagrant/node_modules/berliner/node_modules/vault-cipher/lib/vault-cipher.j
s:40:3)
  at [object Object].Cipher.decrypt (/home/vagrant/node_modules/berliner/node_modules/vault-cipher/lib/vault-cipher.js:7
5:8)
  at new A (/home/vagrant/node_modules/berliner/berliner.coffee:5:120)
  at IncomingMessage.<anonymous> (/home/vagrant/node_modules/berliner/berliner.coffee:14:145)
  at IncomingMessage.EventEmitter.emit (events.js:92:17)
  at _stream_readable.js:919:16
  at process._tickCallback (node.js:419:13)
```

**Comment by rudimk** [comment]
Interestingly, minifying the code seems to resolve it. For now. Will have to play with this further, to figure it out.

**Comment by rudimk** [comment]
Tested on two different Node installations. Works now.

**Comment by rudimk** [comment]
This bug's come up again [here](https://github.com/rudimk/neu-berliner-samples/pull/1). Interestingly, the code is minified, so it seems like something else is causing this.
